litellm_settings:
  callbacks: ["langfuse", "langfuse_otel"] # enable logging

model_list:
  - model_name: claude-bedrock-haiku
    litellm_params:
      model: bedrock/eu.anthropic.claude-haiku-4-5-20251001-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: eu-west-1
    model_info:
      supports_computer_use: True
  - model_name: claude-bedrock-sonnet
    litellm_params:
      model: bedrock/eu.anthropic.claude-sonnet-4-5-20250929-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: eu-west-1
    model_info:
      supports_computer_use: True

general_settings:
  master_key: sk-132608566813
  database_url: litellm-db-cluster-instance-1.cj88ewy8ubmi.eu-west-1.rds.amazonaws.com

# load balancing
router_settings: 
  routing_strategy: simple-shuffle
  fallbacks: []

# add mcp servers
mcp_servers:
  github_mcp:
    url: "https://api.githubcopilot.com/mcp"
    auth_type: oauth2
    client_id: os.environ/GITHUB_OAUTH_CLIENT_ID
    client_secret: os.environ/GITHUB_OAUTH_CLIENT_SECRET